### ISSUE TITLE
Kubernetes can't kill container mqtt-adapter

### ISSUE THREAD

**Issue by rogersacchelli** [OktopUSP/oktopus#219]
Once pod is deployed, if it is required to killed the pod, kubernetes does not have privilegies to kill the pod:
```
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason         Age                   From               Message
  ----     ------         ----                  ----               -------
  Normal   Scheduled      13m                   default-scheduler  Successfully assigned default/mqtt-adapter-564bc76f86-6c6f7 to master1
  Normal   Pulled         13m                   kubelet            Container image "oktopusp/mqtt-adapter:latest" already present on machine
  Normal   Created        13m                   kubelet            Created container mqtt-adapter
  Normal   Started        13m                   kubelet            Started container mqtt-adapter
  Warning  FailedKillPod  11m (x11 over 13m)    kubelet            error killing pod: [failed to "KillContainer" for "mqtt-adapter" with KillContainerError: "rpc error: code = Unknown desc = failed to stop container \"487ff39ca0d59bf8a83b6bdaf69db30c6c8f98d9d5332dbad8efa497b4725f85\": unknown error after kill: runc did not terminate successfully: container_linux.go:418: signaling init process caused: permission denied\n: unknown", failed to "KillPodSandbox" for "a412f10f-2552-4aa0-8393-446e127cc3a4" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to stop container \"487ff39ca0d59bf8a83b6bdaf69db30c6c8f98d9d5332dbad8efa497b4725f85\": failed to kill container \"487ff39ca0d59bf8a83b6bdaf69db30c6c8f98d9d5332dbad8efa497b4725f85\": unknown error after kill: runc did not terminate successfully: container_linux.go:418: signaling init process caused: permission denied\n: unknown"]
  Normal   Killing        3m43s (x47 over 13m)  kubelet            Stopping container mqtt-adapter
vagrant@master1:~/oktopus/backend/services/mtp/mqtt-adapter/internal>
```

It is possible to check this if logged into container and try to kill the application:

```
vagrant@master1:~/oktopus/backend/services/mtp/mqtt-adapter/internal> kubectl exec mqtt-adapter-55b656cf4b-4twlq -it -- sh
/ # ps
PID   USER     TIME  COMMAND
    1 root      0:01 /mqtt-adapter
   16 root      0:00 sh
   23 root      0:00 ps
/ # kill 1
sh: can't kill pid 1: Permission denied
/ #
```

Environment: k3s (openSuse)

Deployment File:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-adapter
  template:
    metadata:
      labels:
        app: mqtt-adapter
    spec:
      containers:
        - name: mqtt-adapter
          image: oktopusp/mqtt-adapter:latest
          resources:
            requests:
              memory: 64Mi
              cpu: 0.1
            limits:
              memory: 128Mi
              cpu: 0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: NATS_URL
              value: "nats:4222"
            - name: NATS_NAME
              value: "mqtt-adapter"
            - name: NATS_VERIFY_CERTIFICATES
              value: "false"
            - name: MQTT_CLIENT_ID
              value: "mqtt-adapter"
            - name: MQTT_USERNAME
              value: ""
            - name: MQTT_PASSWORD
              value: ""
            - name: MQTT_QOS
              value: "1"
            - name: MQTT_SERVICE_HOST
              value: "mqtt"
```
